### ISSUE TITLE
config.json not found

### ISSUE THREAD

**Issue by davej** [shivkanthb/auxiliary-cli#1]
Interested to try this out but got the following error after installing.

```
$ aux


internal/fs/utils.js:230
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/Users/dave/auxdb/config.json'
    at Object.openSync (fs.js:457:3)
    at writeFileSync (fs.js:1282:35)
    at FileSync.read (/Users/dave/n/lib/node_modules/auxcli/node_modules/lowdb/adapters/FileSync.js:46:9)
    at LodashWrapper.db.read (/Users/dave/n/lib/node_modules/auxcli/node_modules/lowdb/lib/main.js:32:21)
    at module.exports (/Users/dave/n/lib/node_modules/auxcli/node_modules/lowdb/lib/main.js:51:13)
    at new Database (/Users/dave/n/lib/node_modules/auxcli/storage.js:13:10)
    at Object.<anonymous> (/Users/dave/n/lib/node_modules/auxcli/index.js:3:10)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/dave/auxdb/config.json'
}
```

**Comment by shivkanthb** [comment]
Did you install the package globally?

**Comment by davej** [comment]
Yes
